spring:
  ai:
    model:
      chat: openai
      embedding: openai
    openai:
      base-url: ${OPENROUTER_BASE_URL}
      api-key: ${OPENROUTER_API_KEY}
      chat:
        options:
          model: ${OPENROUTER_MODEL}
          max-tokens: 1000
        temperature: 0.3
      embedding:
        options:
          model: text-embedding-3-small
          encoding-format: float
    vectorstore:
      pgvector:
        dimensions: 1536
